import React from 'react'
import './Home.css'

import Product from "./Product";


function Home() {
    return (
        <div className="Home">
            <div className="home_container">
                <img className="home_image" src="https://avatar.maplestory.nexon.com/Character/180/HFNBOIHFCFFFENGDCFAACCLDKHKMECNPPFGEAMKFJIJHDKNAKLBJBPGJILDEBKNFIOPHMOKLIICPMFFOKMOFEOHNJPBOMLNLHAFJAMHAFJDLFACJCMPJHBFOBFOEKKNNOBMMEJEHGBDKBHOMMKIKPAPDDBFMPFBAOLPFONNFDCKKLOKAMOHOAPJHOKJELJBOHEGOCPDDAKKLKPNDECIFEFEJLJGANBIJEBLKGPDPPCNCIGAPEHKGMPDHEKBONOJA.png" alt="" />
            </div>

            <div className="home_row">
                <Product id="1" title='MainFunction' price={29.99} image="https://avatar.maplestory.nexon.com/Character/180/HFNBOIHFCFFFENGDCFAACCLDKHKMECNPPFGEAMKFJIJHDKNAKLBJBPGJILDEBKNFIOPHMOKLIICPMFFOKMOFEOHNJPBOMLNLHAFJAMHAFJDLFACJCMPJHBFOBFOEKKNNOBMMEJEHGBDKBHOMMKIKPAPDDBFMPFBAOLPFONNFDCKKLOKAMOHOAPJHOKJELJBOHEGOCPDDAKKLKPNDECIFEFEJLJGANBIJEBLKGPDPPCNCIGAPEHKGMPDHEKBONOJA.png" rating={5} />
                <Product id="2" title='MainFunction' price={29.99} image="https://avatar.maplestory.nexon.com/Character/180/HFNBOIHFCFFFENGDCFAACCLDKHKMECNPPFGEAMKFJIJHDKNAKLBJBPGJILDEBKNFIOPHMOKLIICPMFFOKMOFEOHNJPBOMLNLHAFJAMHAFJDLFACJCMPJHBFOBFOEKKNNOBMMEJEHGBDKBHOMMKIKPAPDDBFMPFBAOLPFONNFDCKKLOKAMOHOAPJHOKJELJBOHEGOCPDDAKKLKPNDECIFEFEJLJGANBIJEBLKGPDPPCNCIGAPEHKGMPDHEKBONOJA.png" rating={5} />
            </div>
            <div className="home_row">
                <Product id="3" title='MainFunction' price={29.99} image="https://avatar.maplestory.nexon.com/Character/180/HFNBOIHFCFFFENGDCFAACCLDKHKMECNPPFGEAMKFJIJHDKNAKLBJBPGJILDEBKNFIOPHMOKLIICPMFFOKMOFEOHNJPBOMLNLHAFJAMHAFJDLFACJCMPJHBFOBFOEKKNNOBMMEJEHGBDKBHOMMKIKPAPDDBFMPFBAOLPFONNFDCKKLOKAMOHOAPJHOKJELJBOHEGOCPDDAKKLKPNDECIFEFEJLJGANBIJEBLKGPDPPCNCIGAPEHKGMPDHEKBONOJA.png" rating={5} />
                <Product id="4" title='MainFunction' price={29.99} image="https://avatar.maplestory.nexon.com/Character/180/HFNBOIHFCFFFENGDCFAACCLDKHKMECNPPFGEAMKFJIJHDKNAKLBJBPGJILDEBKNFIOPHMOKLIICPMFFOKMOFEOHNJPBOMLNLHAFJAMHAFJDLFACJCMPJHBFOBFOEKKNNOBMMEJEHGBDKBHOMMKIKPAPDDBFMPFBAOLPFONNFDCKKLOKAMOHOAPJHOKJELJBOHEGOCPDDAKKLKPNDECIFEFEJLJGANBIJEBLKGPDPPCNCIGAPEHKGMPDHEKBONOJA.png" rating={5} />
                <Product id="5" title='MainFunction' price={29.99} image="https://avatar.maplestory.nexon.com/Character/180/HFNBOIHFCFFFENGDCFAACCLDKHKMECNPPFGEAMKFJIJHDKNAKLBJBPGJILDEBKNFIOPHMOKLIICPMFFOKMOFEOHNJPBOMLNLHAFJAMHAFJDLFACJCMPJHBFOBFOEKKNNOBMMEJEHGBDKBHOMMKIKPAPDDBFMPFBAOLPFONNFDCKKLOKAMOHOAPJHOKJELJBOHEGOCPDDAKKLKPNDECIFEFEJLJGANBIJEBLKGPDPPCNCIGAPEHKGMPDHEKBONOJA.png" rating={5} />
            </div>
            <div className="home_row">
                <Product id="6" title='MainFunction' price={29.99} image="https://avatar.maplestory.nexon.com/Character/180/HFNBOIHFCFFFENGDCFAACCLDKHKMECNPPFGEAMKFJIJHDKNAKLBJBPGJILDEBKNFIOPHMOKLIICPMFFOKMOFEOHNJPBOMLNLHAFJAMHAFJDLFACJCMPJHBFOBFOEKKNNOBMMEJEHGBDKBHOMMKIKPAPDDBFMPFBAOLPFONNFDCKKLOKAMOHOAPJHOKJELJBOHEGOCPDDAKKLKPNDECIFEFEJLJGANBIJEBLKGPDPPCNCIGAPEHKGMPDHEKBONOJA.png" rating={5} />
            </div>
        </div>
    )
}

export default Home
